config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cities, only: [:show, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  attr_accessor :temperature, :conditions, :wind, :humidity

  def weather_api(city_name)
    RestClient.get("api.openweathermap.org/data/2.5/weather?q=#{city_name}&appid=#{ENV['API_KEY']}&units=imperial")
  end
  
  def get_weather
    JSON.parse(weather_api(self.name))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  Dotenv.load
  def index
    @cities = City.all
    @cities.map do |city|
      weather_data = city.get_weather
      city.conditions = weather_data["weather"][0]["main"]
      city.temperature = weather_data["main"]["temp"]
    end
  end

  def show
    @city = City.find(params[:id])
    weather_data = @city.get_weather
    @city.conditions = weather_data["weather"][0]["main"]
    @city.temperature = weather_data["main"]["temp"]
    @city.wind = weather_data["wind"]["speed"]
    @city.humidity = weather_data["main"]["humidity"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/views/cities/index.html.erb
<h2>All Cities</h2>

<ul>
  <% @cities.each do |city| %>
    <a href=<%= city_path(city) %>><li><%= "#{city.name} | #{city.temperature} | #{city.conditions}" %> </li></a>
  <% end %>
</ul>

app/views/cities/show.html.erb
<h2><%= @city.name %></h2>

<h3>Temperature</h3>
  <%= @city.temperature %>
<h3>Conditions</h3>
<%= @city.conditions %>
<h3>Wind</h3>
<%= @city.wind %>
<h3>Humidity</h3>
<%= @city.humidity %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weather</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>